Support reporters
Signed-off-by: Matteo Collina <hello@matteocollina.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,6 +30,19 @@ jobs:
         run: |
           npm install
 
+      - name: Lint
+        run: |
+          npm run lint
+
       - name: Run tests
         run: |
-          npm run test
+          mkdir reports
+          npm run unit -- --reporter spec --reporter junit:reports/${{GITHUB_ACTION$}}.xml
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests                 # Name of the check run which will be created
+          path: reports/*.xml         # Path to test results
+          reporter: jest-junit        # Format of test results
